version: '3'

services:
  app:
    image: node:lts
    container_name: local
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
  go:
    build:
        context: .
        dockerfile: ./app/Dockerfile
    tty: true
    stdin_open: true
    volumes:
        - ./app:/go/src/app
